package com.productbot.service;

public enum PostbackPayload {
	///common
	FILLING_ACTION_PAYLOAD,
	PRODUCT_ACTION_PAYLOAD,
	NAVI_PAYLOAD,
	GET_STARTED_PAYLOAD,
	SET_ROLE_PAYLOAD,
	ORDERINGS_LIST_PAYLOAD,
	GET_ORDER_PAYLOAD,

	//curtain
	ORDER_PAYLOAD,
	ADD_PRODUCT_PAYLOAD,
	DELETE_PRODUCT_PAYLOAD,
	NEXT_PROD_PAYLOAD,
	PREV_PROD_PAYLOAD,
	MENU_PAYLOAD,
	NAVIGATION_MENU,
	CREATE_OWN_PAYLOAD
}
