package com.productbot.service;

public enum QuickReplyPayload {

	PREV_Q_PAYLOAD,
	NEXT_Q_PAYLOAD,
	COMMON_Q_PAYLOAD,
	STOP_Q_PAYLOAD,
	QUESTION_PAYLOAD,
	SET_ROLE_PAYLOAD,
	PUBLISH_BUCKET,
	DELETE_PRODUCT_PAYLOAD,
	GET_ORDER_PAYLOAD,///todo set enum to service pac
	CASH_PAYLOAD,
	CARD_PAYLOAD,
	CREATE_FILLING_PAYLOAD,
	DELETE_FILLING_PAYLOAD,
	UPDATE_PRODUCT_PAYLOAD,
	CT_PRODUCT_PAYLOAD,
}
